version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        build:
            context: ./
            dockerfile: release/ubuntu20.04/Dockerfile
        image: zoneminder
        restart: unless-stopped
        ports:
            - 7878:80
            - 9000:9000
        network_mode: "bridge"
        privileged: true
        shm_size: 512M
        environment:
            - TZ=${TZ:-Australia/Perth}
            - smtp=${smtp}
            - smtpPort=${smtpPort}
            - emailAccount=${emailAccount}
            - emailPasswd=${emailPasswd}
        volumes:
            - zm:/etc/zm
            - events:/var/cache/zoneminder/events
            - images:/var/cache/zoneminder/images
            - mysql:/var/lib/mysql
            - logs:/var/log/zoneminder
volumes:
  zm:
  events:
  images:
  mysql:
  logs:
