version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        build:
            context: ./
            dockerfile: release/ubuntu20.04/Dockerfile
        image: zoneminder
        restart: unless-stopped
        ports:
            - 7878:80
            - 9000:9000
        privileged: true
        shm_size: 512M
        environment:
            - TZ=${TZ:-Australia/Perth}
            - smtp=${smtp}
            - smtpPort=${smtpPort}
            - emailAccount=${emailAccount}
            - emailPasswd=${emailPasswd}
            - ZM_DB_HOST=${ZM_DB_HOST}
            - ZM_DB_USER=${ZM_DB_USER}
            - ZM_DB_PASS=${ZM_DB_PASS}
            - ZM_DB_NAME=${ZM_DB_NAME}
        volumes:
            - ../../dockerdata/zoneminder/zm:/etc/zm
            - ../../dockerdata/zoneminder/events:/var/cache/zoneminder/events
            - ../../dockerdata/zoneminder/images:/var/cache/zoneminder/images
            - ../../dockerdata/zoneminder/mysql:/var/lib/mysql
            - ../../dockerdata/zoneminder/logs:/var/log/zoneminder
        networks:
          external:
           aliases:
                - zoneminder
networks:
   external:
      name: switch
