name: docker-build-and-push-debian-bullseye

env:
  TAG: debian-bullseye                                     # Change me based on image
  REPO: iconzm/packpack                                  # Make sure this matches the DockerHub Repo you're pushing to
  DOCKERFILE_PATH: buildsystem/debian/bullseye/Dockerfile        # Change me based on image

on:
  push:
    paths:
      - 'buildsystem/debian/bullseye/Dockerfile'            # Change me based on image

jobs:
  debian-bulleye:                                          # Change me based on image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REPO }}:${{ env.TAG }}
