name: docker-build-and-push

env:
  tag: ubuntu-impish                                      # Change me based on image
  image: hardenrm/packpack                                  # Make sure this matches the DockerHub Repo you're pushing to
  dockerfile: buildsystem/ubuntu/impish/Dockerfile        # Change me based on image

on:
  push:
    paths:
      - $dockerfile

jobs:
  ubuntu-impish:                                          # Change me based on image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: $image

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: $dockerfile
          platforms: linux/armv7,linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: $tag
